### ISSUE TITLE
Add typings for TypeScript projects

### ISSUE THREAD

**Issue by martellaj** [jasonsjones/queue-fifo#1]
Hey, @jasonsjones. I stumbled across your project while doing some interview prep, and wanted to use your queue implementation so I could quickly move to more complex problems. I'm using TypeScript for my project, so I created a declaration file so I could use it. If you're interested, let me know and I'll prepare a PR so you can add it to your project directly. If not, please let me know and I'll publish it directly myself so anyone in the future could still use it. 😄

**Comment by jasonsjones** [comment]
Hi @martellaj, Yes, very much interested--that would be awesome!  Go ahead and open an PR and I'll get it merged...though likely will not be until after the Thanksgiving weekend.  Thanks a ton!
